### ISSUE TITLE
Not seeing airstage repository result in HACS

### ISSUE THREAD

**Issue by IainMNorman** [danielkaldheim/ha_airstage#1]
<img width="593" alt="image" src="https://github.com/danielkaldheim/ha_airstage/assets/229800/fde76e28-7482-4390-9a0d-1379922db9f8">

**Comment by danielkaldheim** [comment]
Hi,

Thank you for pointing this out! Sorry, it's been a busy week. I'll add the missing bits to make it visible i HACS tonight.

Until it's available in HACS, you can add the repo in custom repo from the menu in HACS.

**Comment by danielkaldheim** [comment]
Pull requested created: https://github.com/hacs/default/pull/2003
