### ISSUE TITLE
Target Tempature will not change

### ISSUE THREAD

**Issue by cookbookhorse** [danielkaldheim/ha_airstage#20]
https://github.com/danielkaldheim/ha_airstage/assets/86279408/38c4b410-7d12-418b-b4d1-682c7e01b652

The target temperature will not change - no error is displayed and no log entry or history event exists to reflect the desired change - it reverts to the already-set temperature after a few seconds as shown in the screen recording.  This happens with any type of lovelace thermostat card

**Comment by robgolding** [comment]
I had a similar issue but it was due to setting the temperature outside of the allowed range. I saw this in the logs:

```pyairstage.airstageAC.AirstageACError: Invalid targetTemperature: 17.0. Value must be 18.0 <= target <= 30.0```

Opened a PR #22 to rectify that.

Also experienced the same thing for a different reason, which was the AC unit responding with a non-200 status code:

```
 Error fetching Fujitsu Airstage data: No valid response after 2 failed attempts. Last error was: Response status not 200. 
```

Not sure why that happened yet!

**Comment by chrisbalmer** [comment]
Try changing HA to use Metric. I'm finding it isn't working when using the widget in US customary.

Working with the API in Postman it appears that the values are in celsius and also it only accepts values rounded to the nearest half degree. i.e. 21.5 is OK but 21.4 is not.

Looking at what the UI is doing, it is sending a F value which is being converted to C which creates a value that is not rounded to the nearest half degree. This causes the API to not respond, hanging the set command which results in a delay before HA realizes that the value is the old one still.

Changing HA to metric fixes this as it then uses the actual value set in the widget which is configured to allow increments in half degrees and doesn't then convert the value creating a long decimal.

The long term fix I believe would be adding a couple lines to round the temperature value to the nearest half degree before multiplying by 10 and sending in the API code at https://github.com/danielkaldheim/pyairstage/blob/a0eeb9433d612d8a154c12f6c0602a8c5021fa81/pyairstage/airstageAC.py#L150

**Comment by chrisbalmer** [comment]
I plan on submitting a PR to the pyairstage repo with the fix later today. Unsure how long it will take for the owner to review and merge. You can edit the files on your HA install and add them in. Just change:

```
        actual_target = int(target_temperature * 10)
```

to 

```
        rounded_temp = round(target_temperature * 2) / 2
        actual_target = int(rounded_temp * 10)
```

in `/config/deps/lib/python3.11/site-packages/pyairstage/airstageAC.py` then restart HA.

**Comment by cookbookhorse** [comment]
Thanks - I can confirm that changing the the min/max values didn't help my
issue, as suggested in https://github.com/danielkaldheim/ha_airstage/pull/22

Switching HA units from F to C fixes this 100%

I'm running HA in Docker, and having trouble finding the airstageAC.py file
to edit.  Will keep working on it.

**Comment by cookbookhorse** [comment]
Nevermind - found it - in docker it's /usr/local/lib/python3.11/site-packages/pyairstage.  Fix works for me.  thanks!

**Comment by mcfloyd** [comment]
I am a stupid American and would also like this change.  For some reason I cannot figure out how to override the pyairstage file on my raspberry pi home assistant.

**Comment by ajyounge** [comment]
Can confirm this issue in US as well and it’s a major blocker to basic usage, and asking my partner to use Celcius is like asking them to never touch the thermostat. 

I do not se a PR in Pyairstage that addresses this yet. @chrisbalmer is this coming, merged directly, or need help?

**Comment by danielkaldheim** [comment]
Hopefully fixed with https://github.com/danielkaldheim/pyairstage/pull/8. Thanks @mcfloyd
