### ISSUE TITLE
"Minimum Heat" HVAC operation mode

### ISSUE THREAD

**Issue by andrewmooreio** [danielkaldheim/ha_airstage#27]
Hi,

There is an additional HVAC mode available in the Airstage app that isn't exposed through this HA integration, "Minimum Heat", which sets the air conditioner to keep temperatures above freezing with a target temperature of 10 °C. Is it possible to expose this through the integration?

![IMG_0483](https://github.com/danielkaldheim/ha_airstage/assets/20435317/c7875a18-2b29-495e-870d-b9b599bcaf4e)

Many thanks.

**Comment by jshiell** [comment]
Looks like it's not available in the API library, I've created a [PR to add it](https://github.com/danielkaldheim/pyairstage/pull/5).

**Comment by danielkaldheim** [comment]
Thank you @jshiell!
Your PR (https://github.com/danielkaldheim/pyairstage/pull/7) is merged. Feel free to create a new PR within this repo to add the feature to the integration.
