### ISSUE TITLE
Changing desired/set temp when unit is off causes error

### ISSUE THREAD

**Issue by ptruman** [danielkaldheim/ha_airstage#36]
I've noticed some use cases where family are wanting to set the temp before selecting the mode (i.e. heat/cool).
This is because the climate UI has the dial/buttons above the mode - so "not the integrations" fault.

If a unit is off, and someone tries to set temp, you get this:

`Failed to call service climate/set_temperature. cannot access local variable 'min_temp' where it is not associated with a value_`

Is it possible to store the last known set temp, and allow it to amended and "sent" to the unit when a mode is selected?
(using V1.1.8 of the integration via HACS)

**Comment by GastonHP** [comment]
I have the same issue!

**Comment by donkawechico** [comment]
Same here!

**Comment by ptruman** [comment]
I've found this is likely due to HASS and not the plugin.
If you load the attributes for an Indoor Unit now, the CURRENT TEMP is an
attribute, not a sensor value.
The sensor value "dies" (unavailable) when the unit is off - but the
attribute is always there.
You can build a sensor to update from the value....
