### ISSUE TITLE
Cloud implementation

### ISSUE THREAD

**Issue by danielkaldheim** [danielkaldheim/ha_airstage#7]
- [ ] Update documentation
- [ ] Add warning text about IP-Block
- [ ] Change default configuration to local

https://community.home-assistant.io/t/fujitsu-air-conditioning-integration-airstage-dongle/589679/136

**Comment by ptruman** [comment]
I'd suggest REMOVING the Cloud integration - see comments on the HASS forum re: getting unblocked.
